Dan floating action button
green-fox-academy/vulpes-gitinder-frontend pull request #58
Opened 2019-01-28 12:12 UTC by kolekd

2019-01-29 16:01 UTC, adamgyulavari requested changes

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/activity/MainActivity.java
> +            mViewPager.setCurrentItem(1);
@kolekd have a moveToMatchesFragment() method

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/activity/MainActivity.java
> +    public void setupViewPager (NonSwipeableViewPager viewPager){
@kolekd why add the space?

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/activity/MainActivity.java
> +    public void toLogin () {
@kolekd and here?

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/adapter/MatchAdapter.java
> +            lastMessage = matchList.get(position).getMessages().get(matchList.get(position).getMessages().size() - 1).getMessage();
@kolekd we should have a getLastMessage() on the Match

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/adapter/MatchAdapter.java
> +        if(matchList.get(position).getMessages().size() < 1){
@kolekd we should have a isNew() method on the match

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/adapter/MatchAdapter.java
> +            messagesButton.setOnClickListener(v -> {
@kolekd this should be only in development version

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +                sharedPreferencesListenerDude();
@kolekd you don't have to setup the listener every time there's a change

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +                sharedPreferences.edit().putString(Constants.MATCHES_COUNT,
@kolekd this is a nice idea, though I think it'd be better to have this functionality in a MatchService

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +                sharedPreferences.edit().putString(Constants.MATCHES_COUNT,
MatchService that can
- manage and update matches
- get the number of new matches

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +                sharedPreferences.edit().putString(Constants.MATCHES_COUNT,
just use the service here

2019-01-29 16:01 UTC, adamgyulavari commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +        floatingActionButton = getActivity().findViewById(R.id.floating_action_button);
@kolekd this is definitely shouldn't be here, since it's in the activity this should be handled there

2019-01-30 10:22 UTC, kolekd commented on app/src/main/java/com/greenfox/gitinder/fragment/main/MatchesFragment.java
> +                sharedPreferencesListenerDude();
if I put it at above the 'matchAdapter.registerAdapterDataObserver(new ....)' method, on the line 73, the floating button doesnt appear when I add the new matches using the button. It only appears when I interact with the matches one more time (for example adding a message to one fo the matches makes the button appear with the number 5 on it).

2019-01-31 10:38 UTC, adamgyulavari approved these changes

2019-01-31 10:38 UTC, merged